[package]
name = "riichi_mahjong_rs"
version = "0.1.0"
authors = ["hi_go <me@clutte.red>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.1"
strum = "0.21"
strum_macros = "0.21"
anyhow = "1.0"
